using System.Linq;
using Content.Shared._Arcane.TTS;
using Content.Shared.Preferences;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Client.UserInterface.Controls;
using Robust.Shared.Prototypes;
using Content.Client.Stylesheets;
using Content.Shared.Humanoid;

namespace Content.Client._Arcane.TTS;

[GenerateTypedNameReferences]
public sealed partial class TTSTab : Control
{
    [Dependency] private IPrototypeManager _prototypeManager = default!;

    public event Action<string>? OnVoiceSelected;
    public event Action<string>? OnPreviewRequested;

    private List<TTSVoicePrototype> _allVoices = new();
    private List<TTSVoicePrototype> _filteredVoices = new();
    private string? _selectedVoiceId;
    private Sex _selectedSex = Sex.Male;

    public TTSTab()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        var sexGroup = new ButtonGroup(isNoneSetAllowed: false);
        MaleButton.Group = sexGroup;
        FemaleButton.Group = sexGroup;

        MaleButton.OnPressed += _ => SetSelectedSex(Sex.Male);
        FemaleButton.OnPressed += _ => SetSelectedSex(Sex.Female);
        SearchEdit.OnTextChanged += OnSearchChanged;
    }

    private void SetSelectedSex(Sex sex)
    {
        _selectedSex = sex;
        if (sex == Sex.Male)
            MaleButton.Pressed = true;
        else
            FemaleButton.Pressed = true;
        UpdateResults();
    }

    private void OnSearchChanged(LineEdit.LineEditEventArgs args)
    {
        UpdateResults();
    }

    private void UpdateResults()
    {
        VoicesGrid.RemoveAllChildren();
        _filteredVoices.Clear();

        var searchText = SearchEdit.Text.ToLowerInvariant();
        var sexCount = 0;

        foreach (var voice in _allVoices)
        {
            if (!HumanoidCharacterProfile.CanHaveVoice(voice, _selectedSex))
                continue;

            sexCount++;

            var name = Loc.GetString(voice.Name).ToLowerInvariant();

            if (string.IsNullOrEmpty(searchText) ||
                name.Contains(searchText) ||
                voice.ID.ToLowerInvariant().Contains(searchText))
            {
                _filteredVoices.Add(voice);
            }
        }

        foreach (var voice in _filteredVoices)
        {
            var displayName = Loc.GetString(voice.Name);

            var voiceContainer = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                HorizontalExpand = true,
                VerticalAlignment = VAlignment.Center
            };

            var selectButton = new Button
            {
                Text = displayName,
                ToolTip = voice.ID,
                HorizontalExpand = true,
                StyleClasses = { StyleClass.ButtonOpenRight }
            };

            if (voice.ID == _selectedVoiceId)
            {
                selectButton.AddStyleClass(StyleClass.Negative);
            }

            selectButton.OnPressed += _ =>
            {
                OnVoiceSelected?.Invoke(voice.ID);
            };

            var previewButton = new Button
            {
                Text = Loc.GetString("humanoid-profile-editor-voice-play"),
                MinWidth = 30,
                ToolTip = Loc.GetString("humanoid-profile-editor-voice-tooltip-play"),
                StyleClasses = { StyleClass.ButtonOpenLeft }
            };

            previewButton.OnPressed += _ =>
            {
                OnPreviewRequested?.Invoke(voice.ID);
            };

            voiceContainer.AddChild(selectButton);
            voiceContainer.AddChild(previewButton);

            VoicesGrid.AddChild(voiceContainer);
        }

        ResultsLabel.Text = Loc.GetString("humanoid-profile-editor-voice-match",
            ("filtered", _filteredVoices.Count), ("all", sexCount));
    }

    public void UpdateControls(HumanoidCharacterProfile? profile, Sex sex)
    {
        if (profile == null)
            return;

        _selectedVoiceId = profile.Voice;

        _allVoices = _prototypeManager
            .EnumeratePrototypes<TTSVoicePrototype>()
            .Where(o => o.RoundStart)
            .OrderBy(o => Loc.GetString(o.Name))
            .ToList();

        SetSelectedSex(MapSex(sex));
    }

    /// <summary>
    /// Voices are not restricted to a specific sex, but the tab opens on the sex
    /// that matches the character's current sex by default.
    /// </summary>
    private static Sex MapSex(Sex sex)
    {
        return sex switch
        {
            Sex.Male => Sex.Male,
            Sex.Female => Sex.Female,
            _ => Sex.Male,
        };
    }

    public void SetSelectedVoice(string voiceId)
    {
        _selectedVoiceId = voiceId;
        UpdateResults();
    }
}
